#!/usr/bin/env python3
"""Cross-read parity inventory: libdxfrw dispatch/filter vs seed curated rows.

Auto columns: name, lib_dispatched, lib_filter_override.
Curated seed: S tier, direction, priority (never auto F/G).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "libraries/libdxfrw/CROSS_READ_PARITY_STATUS.md"
SEED = ROOT / "libraries/libdxfrw/cross_read_parity_seed.json"


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def iface_adds(text: str) -> set[str]:
    return set(re.findall(r"virtual void (add\w+)\s*\(", text))


def filter_overrides(cpp: str, header: str) -> set[str]:
    names = set(re.findall(r"RS_FilterDXFRW::(add\w+)\s*\(", cpp))
    names |= set(re.findall(r"void\s+(add\w+)\s*\(", header))
    return names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("-o", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    iface = read(ROOT / "libraries/libdxfrw/src/drw_interface.h")
    filt_cpp = read(ROOT / "librecad/src/lib/filters/rs_filterdxfrw.cpp")
    filt_h = read(ROOT / "librecad/src/lib/filters/rs_filterdxfrw.h")
    adds = sorted(iface_adds(iface))
    overrides = filter_overrides(filt_cpp, filt_h)
    missing = [a for a in adds if a not in overrides]

    seed = {}
    if SEED.exists():
        seed = json.loads(SEED.read_text(encoding="utf-8"))

    rows = []
    for name in adds:
        srow = seed.get(name, {})
        rows.append(
            {
                "name": name,
                "lib_dispatched": True,
                "lib_filter_override": name in overrides,
                "lib_S": srow.get("S", "T" if name in overrides else "R"),
                "lib_L": srow.get(
                    "L",
                    "metadata-sidecar"
                    if name in overrides
                    else "libdxfrw-only",
                ),
                "direction": srow.get("direction", "→librecad" if name not in overrides else "both"),
                "priority": srow.get("priority", "P1" if name not in overrides else "P2"),
                "notes": srow.get("notes", ""),
            }
        )

    lines = [
        "# Cross-Read Parity Status (LibreCAD)",
        "",
        f"Generated by `scripts/dwg_cross_read_parity_inventory.py`.",
        "",
        f"- Interface add* hooks: **{len(adds)}**",
        f"- Filter overrides: **{len(overrides)}**",
        f"- Missing filter overrides: **{len(missing)}**",
        "",
        "## Missing filter overrides (auto)",
        "",
    ]
    for m in missing:
        lines.append(f"- `{m}`")
    lines += [
        "",
        "## Matrix (auto + curated seed)",
        "",
        "| name | filter_override | lib_S | lib_L | priority | direction |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        if r["priority"] in ("P0", "P1") or not r["lib_filter_override"]:
            lines.append(
                f"| `{r['name']}` | {r['lib_filter_override']} | {r['lib_S']} | {r['lib_L']} | {r['priority']} | {r['direction']} |"
            )

    p0p1 = [r for r in rows if r["priority"] in ("P0", "P1")]
    lines += ["", f"## P0/P1 seed rows: {len(p0p1)}", ""]
    for r in p0p1:
        allow = r.get("notes") or ""
        status = "exposed" if r["lib_filter_override"] else ("allowlisted" if "allowlist" in allow.lower() else "open")
        lines.append(f"- `{r['name']}`: {status} (S={r['lib_S']}, L={r['lib_L']}) {allow}")

    text = "\n".join(lines) + "\n"
    if args.write:
        args.o.parent.mkdir(parents=True, exist_ok=True)
        args.o.write_text(text, encoding="utf-8")
        print(f"wrote {args.o}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
