//
//  ResolveTests.swift
//  CADEngineTests
//
//  Verifies the ADR-001 computed-geometry path: resolve() and boundingBox()
//  for the seed entity set, plus the sagitta tessellation error bound and pen
//  .byLayer resolution.
//
//  GPLv2-or-later (LibreCAD derivative).
//

import Testing
import Foundation
@testable import CADEngine

private let tol = 1e-9

@Suite("resolve() computed geometry")
struct ResolveTests {

    // MARK: - Line

    @Test("line resolves to a 2-point open polyline")
    func lineResolves() {
        let e = EntityRecord(id: EntityID(1), kind: .line(LineData(start: Vector(0, 0), end: Vector(10, 5))))
        let geo = e.resolve()
        #expect(geo.polylines.count == 1)
        let poly = geo.polylines[0]
        #expect(poly.points.count == 2)
        #expect(poly.closed == false)
        #expect(poly.points[0] == Vector(0, 0))
        #expect(poly.points[1] == Vector(10, 5))
    }

    @Test("line bounding box is the endpoint extent")
    func lineBBox() {
        let e = EntityRecord(id: EntityID(1), kind: .line(LineData(start: Vector(2, 7), end: Vector(10, 1))))
        let box = e.boundingBox()
        #expect(box.min == Vector(2, 1))
        #expect(box.max == Vector(10, 7))
    }

    // MARK: - Point

    @Test("point resolves to a degenerate single-point polyline")
    func pointResolves() {
        let e = EntityRecord(id: EntityID(1), kind: .point(PointData(position: Vector(3, 4))))
        let geo = e.resolve()
        #expect(geo.polylines.count == 1)
        #expect(geo.polylines[0].points == [Vector(3, 4)])
    }

    // MARK: - Circle

    @Test("circle tessellates to a closed ring, every point within tolerance of radius")
    func circleResolves() {
        let r = 25.0
        let center = Vector(5, -3)
        let ctx = ResolveContext(tessellationTolerance: 0.01)
        let e = EntityRecord(id: EntityID(1), kind: .circle(CircleData(center: center, radius: r)))
        let geo = e.resolve(ctx)
        #expect(geo.polylines.count == 1)
        let poly = geo.polylines[0]
        #expect(poly.closed == true)
        #expect(poly.points.count >= 3)
        // Every tessellated vertex lies on the circle (radius preserved exactly
        // — they're generated by polar(), so they're ON the circle, not chords).
        for p in poly.points {
            #expect(abs(p.distance(to: center) - r) < tol)
        }
    }

    @Test("sagitta: finer tolerance yields more circle segments")
    func sagittaRefines() {
        let coarse = Tessellation.segmentCount(radius: 100, sweep: 2 * .pi, tolerance: 1.0)
        let fine = Tessellation.segmentCount(radius: 100, sweep: 2 * .pi, tolerance: 0.01)
        #expect(fine > coarse)
        // Chord error bound: for the chosen segment count, r*(1-cos(theta/2)) <= tol.
        let tolerance = 0.1
        let n = Tessellation.segmentCount(radius: 50, sweep: 2 * .pi, tolerance: tolerance)
        let theta = (2 * Double.pi) / Double(n)
        let sagitta = 50.0 * (1 - cos(theta / 2))
        #expect(sagitta <= tolerance + 1e-9)
    }

    @Test("circle bounding box is the analytic r-box")
    func circleBBox() {
        let e = EntityRecord(id: EntityID(1), kind: .circle(CircleData(center: Vector(10, 20), radius: 5)))
        let box = e.boundingBox()
        #expect(box.min == Vector(5, 15))
        #expect(box.max == Vector(15, 25))
    }

    // MARK: - Arc

    @Test("arc endpoints are correct")
    func arcEndpoints() {
        // Quarter arc from angle 0 to pi/2, radius 10, center origin, CCW.
        let e = EntityRecord(
            id: EntityID(1),
            kind: .arc(ArcData(center: Vector(0, 0), radius: 10, startAngle: 0, endAngle: .pi / 2, reversed: false))
        )
        let geo = e.resolve(ResolveContext(tessellationTolerance: 0.001))
        let pts = geo.polylines[0].points
        #expect(pts.count >= 2)
        // First point at (10, 0), last at (0, 10).
        #expect(pts.first!.distance(to: Vector(10, 0)) < 1e-6)
        #expect(pts.last!.distance(to: Vector(0, 10)) < 1e-6)
    }

    @Test("reversed arc endpoints swap travel direction")
    func reversedArcEndpoints() {
        // Reversed (CW) arc still starts at startAngle and ends at endAngle.
        let e = EntityRecord(
            id: EntityID(1),
            kind: .arc(ArcData(center: Vector(0, 0), radius: 10, startAngle: 0, endAngle: .pi / 2, reversed: true))
        )
        let geo = e.resolve(ResolveContext(tessellationTolerance: 0.001))
        let pts = geo.polylines[0].points
        #expect(pts.first!.distance(to: Vector(10, 0)) < 1e-6)
        #expect(pts.last!.distance(to: Vector(0, 10)) < 1e-6)
        // Going CW from 0, an intermediate point dips below the x-axis (y < 0).
        let mid = pts[pts.count / 2]
        #expect(mid.y < 0)
    }

    // MARK: - Polyline

    @Test("straight polyline passes vertices through")
    func straightPolyline() {
        let d = PolylineData(vertices: [
            PolylineVertex(point: Vector(0, 0)),
            PolylineVertex(point: Vector(10, 0)),
            PolylineVertex(point: Vector(10, 10)),
        ], closed: false)
        let e = EntityRecord(id: EntityID(1), kind: .polyline(d))
        let geo = e.resolve()
        #expect(geo.polylines[0].points == [Vector(0, 0), Vector(10, 0), Vector(10, 10)])
        #expect(geo.polylines[0].closed == false)
    }

    @Test("bulged polyline segment expands into an arc run")
    func bulgedPolyline() {
        // A semicircle bulge (bulge = 1 => 180-degree included angle) from
        // (0,0) to (10,0): the run should arch up and stay within radius 5.
        let d = PolylineData(vertices: [
            PolylineVertex(point: Vector(0, 0), bulge: 1),
            PolylineVertex(point: Vector(10, 0)),
        ], closed: false)
        let e = EntityRecord(id: EntityID(1), kind: .polyline(d))
        let geo = e.resolve(ResolveContext(tessellationTolerance: 0.01))
        let pts = geo.polylines[0].points
        #expect(pts.count > 2)  // tessellated, not a straight chord
        #expect(pts.first!.distance(to: Vector(0, 0)) < 1e-6)
        #expect(pts.last!.distance(to: Vector(10, 0)) < 1e-6)
        // Apex around (5, 5) for a unit (semicircle) bulge of chord 10 (radius 5).
        let maxY = pts.map(\.y).max()!
        #expect(abs(maxY - 5) < 0.1)
    }

    // MARK: - Pen .byLayer resolution

    @Test("pen .byLayer resolves to the layer attributes via the context hook")
    func penByLayerResolves() {
        let layerColor = RGBAColor(0.2, 0.4, 0.6)
        let ctx = ResolveContext(
            tessellationTolerance: 0.05,
            layerAttributes: { _ in ResolvedPen(color: layerColor, lineType: .dashed, lineWidth: .millimeters(0.35)) }
        )
        let e = EntityRecord(
            id: EntityID(1),
            pen: Pen(lineColor: .byLayer, lineType: .byLayer, lineWidth: .byLayer),
            kind: .line(LineData(start: Vector(0, 0), end: Vector(1, 1)))
        )
        let resolved = e.resolve(ctx).polylines[0].pen
        #expect(resolved.color == layerColor)
        #expect(resolved.lineType == .dashed)
        #expect(resolved.lineWidth == .millimeters(0.35))
    }

    @Test("explicit pen overrides the layer")
    func explicitPenWins() {
        let explicit = RGBAColor(1, 0, 0)
        let e = EntityRecord(
            id: EntityID(1),
            pen: Pen(lineColor: .explicit(explicit), lineType: .solid, lineWidth: .default),
            kind: .line(LineData(start: Vector(0, 0), end: Vector(1, 1)))
        )
        let resolved = e.resolve().polylines[0].pen
        #expect(resolved.color == explicit)
    }
}

// MARK: - AABB

@Suite("AABB")
struct AABBTests {
    @Test("empty union absorbs the other box")
    func emptyUnion() {
        let a = AABB.empty
        let b = AABB(points: [Vector(0, 0), Vector(5, 5)])
        #expect(a.union(b) == b)
        #expect(b.union(a) == b)
    }

    @Test("expand and contains")
    func expandContains() {
        var box = AABB.empty
        box.expand(toInclude: Vector(0, 0))
        box.expand(toInclude: Vector(10, 4))
        #expect(box.contains(Vector(5, 2)))
        #expect(!box.contains(Vector(-1, 2)))
        #expect(box.contains(Vector(0, 0)))   // boundary
        #expect(box.contains(Vector(10, 4)))  // boundary
    }

    @Test("union of two boxes")
    func union() {
        let a = AABB(points: [Vector(0, 0), Vector(5, 5)])
        let b = AABB(points: [Vector(3, -2), Vector(8, 4)])
        let u = a.union(b)
        #expect(u.min == Vector(0, -2))
        #expect(u.max == Vector(8, 5))
    }
}
